### -----------------------------------------
### External DNS
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: external-dns-charts
spec:
  charts:
    # renovate: datasource=helm depName=external-dns registryUrl=https://kubernetes-sigs.github.io/external-dns
    - name: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns
      version: 1.20.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: external-dns-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # renovate: datasource=docker
    - name: registry.k8s.io/external-dns/external-dns:v0.20.0

### -----------------------------------------
### Kube-VIP
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: kube-vip-charts
spec:
  charts:
    # renovate: datasource=helm depName=kube-vip registryUrl=https://kube-vip.github.io/helm-charts
    - name: kube-vip
      repoURL: https://kube-vip.github.io/helm-charts
      version: 0.9.4
    # renovate: datasource=helm depName=kube-vip-cloud-provider registryUrl=https://kube-vip.github.io/helm-charts
    - name: kube-vip-cloud-provider
      repoURL: https://kube-vip.github.io/helm-charts
      version: 0.2.9
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: kube-vip-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # renovate: datasource=docker
    - name: ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.12
    # renovate: datasource=docker
    - name: ghcr.io/kube-vip/kube-vip:v0.9.2

### -----------------------------------------
### Splunk
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: splunk-hauler-charts
spec:
  charts:
    # renovate: datasource=helm depName=splunk-enterprise registryUrl=https://splunk.github.io/splunk-operator
    - name: splunk-enterprise
      repoURL: https://splunk.github.io/splunk-operator
      version: 2.8.1
    # renovate: datasource=helm depName=splunk-operator registryUrl=https://splunk.github.io/splunk-operator
    - name: splunk-operator
      repoURL: https://splunk.github.io/splunk-operator
      version: 2.8.1
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: splunk-hauler-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # renovate: datasource=docker
    - name: docker.io/splunk/splunk:9.4.7
    # renovate: datasource=docker
    - name: docker.io/splunk/splunk-operator:2.8.1
    # renovate: datasource=docker
    - name: quay.io/brancz/kube-rbac-proxy:v0.20.1

### -----------------------------------------
### Cribl
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: cribl-hauler-charts
spec:
  charts:
    # renovate: datasource=helm depName=logstream-leader registryUrl=https://criblio.github.io/helm-charts
    - name: logstream-leader
      repoURL: https://criblio.github.io/helm-charts
      version: 4.15.1
    # renovate: datasource=helm depName=logstream-workergroup registryUrl=https://criblio.github.io/helm-charts
    - name: logstream-workergroup
      repoURL: https://criblio.github.io/helm-charts
      version: 4.15.1
    # renovate: datasource=helm depName=edge registryUrl=https://criblio.github.io/helm-charts
    - name: edge
      repoURL: https://criblio.github.io/helm-charts
      version: 4.15.1
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: cribl-hauler-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # renovate: datasource=docker
    - name: docker.io/cribl/cribl:4.15.1
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: cribl-hauler-files
spec:
  files:
    - path: https://cdn.cribl.io/dl/4.12.2/cribl-4.12.2-4b17c8d4-linux-x64.tgz
    - path: https://cdn.cribl.io/dl/4.12.2/cribl-4.12.2-4b17c8d4-linux-x64.tgz.sha256
    - path: https://cdn.cribl.io/dl/4.12.2/cribl-4.12.2-4b17c8d4-linux-x64.tgz.md5
    - path: https://cdn.cribl.io/dl/4.12.2/cribl-4.12.2-4b17c8d4-win32-x64.msi
    - path: https://cdn.cribl.io/dl/4.12.2/cribl-4.12.2-4b17c8d4-win32-x64.msi.sha256
    - path: https://cdn.cribl.io/dl/4.12.2/cribl-4.12.2-4b17c8d4-win32-x64.msi.md5
