### -----------------------------------------
### Datashim
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: datashim-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # renovate: datasource=docker
    - name: registry.k8s.io/sig-storage/csi-attacher:v4.9.0
    # renovate: datasource=docker
    - name: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.14.0
    # renovate: datasource=docker
    - name: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
    # renovate: datasource=docker
    - name: quay.io/datashim-io/generate-keys:0.4.1
    # renovate: datasource=docker
    - name: quay.io/datashim-io/dataset-operator:0.4.1
    # renovate: datasource=docker
    - name: quay.io/datashim-io/csi-s3:latest
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: datashim-charts
spec:
  charts:
    # renovate: datasource=helm depName=datashim-charts registryUrl=https://datashim-io.github.io/datashim
    - name: datashim-charts
      repoURL: https://datashim-io.github.io/datashim
      version: 0.4.1

### -----------------------------------------
### External DNS
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: external-dns-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # renovate: datasource=docker
    - name: registry.k8s.io/external-dns/external-dns:v0.18.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: external-dns-charts
spec:
  charts:
    # renovate: datasource=helm depName=external-dns registryUrl=https://kubernetes-sigs.github.io/external-dns
    - name: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns
      version: 1.17.0

### -----------------------------------------
### Kube-VIP
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: kube-vip-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # renovate: datasource=docker
    - name: ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.12
    # renovate: datasource=docker
    - name: ghcr.io/kube-vip/kube-vip:v0.9.2
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: kube-vip-charts
spec:
  charts:
    # renovate: datasource=helm depName=kube-vip registryUrl=https://kube-vip.github.io/helm-charts
    - name: kube-vip
      repoURL: https://kube-vip.github.io/helm-charts
      version: 0.6.6
    # renovate: datasource=helm depName=kube-vip-cloud-provider registryUrl=https://kube-vip.github.io/helm-charts
    - name: kube-vip-cloud-provider
      repoURL: https://kube-vip.github.io/helm-charts
      version: 0.2.5

### -----------------------------------------
### Splunk
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: splunk-hauler-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # renovate: datasource=docker
    - name: docker.io/splunk/splunk:9.4.3
    # renovate: datasource=docker
    - name: docker.io/splunk/splunk-operator:2.8.0
    # renovate: datasource=docker
    - name: quay.io/brancz/kube-rbac-proxy:v0.19.1

---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: splunk-hauler-charts
spec:
  charts:
    # renovate: datasource=helm depName=splunk-enterprise registryUrl=https://splunk.github.io/splunk-operator
    - name: splunk-enterprise
      repoURL: https://splunk.github.io/splunk-operator
      version: 2.8.0
    # renovate: datasource=helm depName=splunk-operator registryUrl=https://splunk.github.io/splunk-operator
    - name: splunk-operator
      repoURL: https://splunk.github.io/splunk-operator
      version: 2.8.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: splunk-uf-hauler-files
spec:
  files:
    - path: https://download.splunk.com/products/universalforwarder/releases/9.3.2/linux/splunkforwarder-9.3.2-d8bb32809498.x86_64.rpm
    - path: https://download.splunk.com/products/universalforwarder/releases/9.3.2/windows/splunkforwarder-9.3.2-d8bb32809498-x64-release.msi

### -----------------------------------------
### Cribl
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: cribl-hauler-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    # renovate: datasource=docker
    - name: docker.io/cribl/cribl:4.12.2
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: cribl-hauler-charts
spec:
  charts:
    # renovate: datasource=helm depName=logstream-leader registryUrl=https://criblio.github.io/helm-charts
    - name: logstream-leader
      repoURL: https://criblio.github.io/helm-charts
      version: 4.12.2
    # renovate: datasource=helm depName=logstream-workergroup registryUrl=https://criblio.github.io/helm-charts
    - name: logstream-workergroup
      repoURL: https://criblio.github.io/helm-charts
      version: 4.12.2
    # renovate: datasource=helm depName=edge registryUrl=https://criblio.github.io/helm-charts
    - name: edge
      repoURL: https://criblio.github.io/helm-charts
      version: 4.12.2
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: cribl-hauler-files
spec:
  files:
    - path: https://cdn.cribl.io/dl/4.9.3/cribl-4.9.3-25d56bdd-linux-x64.tgz
