### -----------------------------------------
### Datashim
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: datashim-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    - name: registry.k8s.io/sig-storage/csi-attacher:v4.7.0
    - name: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.12.0
    - name: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0
    - name: quay.io/datashim-io/generate-keys:0.4.1
    - name: quay.io/datashim-io/dataset-operator:0.4.1
    - name: quay.io/datashim-io/csi-s3:latest
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: datashim-charts
spec:
  charts:
    - name: datashim-charts
      repoURL: https://datashim-io.github.io/datashim
      version: 0.4.1

### -----------------------------------------
### External DNS
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: external-dns-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    - name: registry.k8s.io/external-dns/external-dns:v0.15.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: external-dns-charts
spec:
  charts:
    - name: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns
      version: 1.15.0

### -----------------------------------------
### Kube-VIP
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: kube-vip-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    - name: ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.10
    - name: ghcr.io/kube-vip/kube-vip:v0.8.7
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: kube-vip-charts
spec:
  charts:
    - name: kube-vip
      repoURL: https://kube-vip.github.io/helm-charts
      version: 0.6.3
    - name: kube-vip-cloud-provider
      repoURL: https://kube-vip.github.io/helm-charts
      version: 0.2.2

### -----------------------------------------
### Splunk
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: splunk-hauler-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    - name: docker.io/splunk/splunk:9.3.2
    - name: docker.io/splunk/splunk-operator:2.7.0
    - name: quay.io/brancz/kube-rbac-proxy:v0.13.1

---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: splunk-hauler-charts
spec:
  charts:
    - name: splunk-enterprise
      repoURL: https://splunk.github.io/splunk-operator
      version: 2.7.0
    - name: splunk-operator
      repoURL: https://splunk.github.io/splunk-operator
      version: 2.7.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: splunk-uf-hauler-files
spec:
  files:
    - path: https://download.splunk.com/products/universalforwarder/releases/9.3.2/linux/splunkforwarder-9.3.2-d8bb32809498.x86_64.rpm
    - path: https://download.splunk.com/products/universalforwarder/releases/9.3.2/windows/splunkforwarder-9.3.2-d8bb32809498-x64-release.msi

### -----------------------------------------
### Cribl
### -----------------------------------------
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: cribl-hauler-images
  annotations:
    hauler.dev/platform: linux/amd64
spec:
  images:
    - name: docker.io/cribl/cribl:4.9.3
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: cribl-hauler-charts
spec:
  charts:
    - name: logstream-leader
      repoURL: https://criblio.github.io/helm-charts
      version: 4.9.3
    - name: logstream-workergroup
      repoURL: https://criblio.github.io/helm-charts
      version: 4.9.3
    - name: edge
      repoURL: https://criblio.github.io/helm-charts
      version: 4.9.3
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: cribl-hauler-files
spec:
  files:
    - path: https://cdn.cribl.io/dl/4.9.3/cribl-4.9.3-25d56bdd-linux-x64.tgz
